variable "name" {}
variable "account_name" {}
variable "region" {}
variable "private_ip_address_allocation" {}
variable "unique_id" {}
variable "address_space" {}
variable "address_prefixes" {}
variable "allocation_method" {}
variable "idle_timeout_in_minutes" {}

## security rule
variable "priority" {}
variable "direction" {}
variable "access" {}
variable "protocol_tcp" {}
variable "protocol_udp" {}
variable "source_port_range" {}
variable "source_address_prefixes" {}
variable "destination_address_prefix" {}
variable "destination_tcpport_ranges" {}
variable "destination_udpport_ranges" {}