########################
####    Required    ####
########################
variable "admin_password" {
  description = "The Password which should be used for the local-administrator on this virtual machine"
  type        = string
  sensitive   = true
  validation {
    condition     = length(var.admin_password) >= 8
    error_message = "The admin_password value must be at least 8 characters in length"
  }
}

#ICO by Kubex Name of the system.
variable "name" {
  default = "test"
}

variable "Kubex_recommendations" {
  type = map(map(string))
  #sample map of map this would be generated by Kubex provided as a .auto.tfvars file that would have all the systems and info listed. 
  #In the file there would be multiple systems defined in this case it just has 1 called test. 
  #To see how it would work you can change the approvalType from all to na. As all assumes you have approved all changes and na would be used to say haven't approved the change and just want to make the system self-aware. 
  default = { 
    test = {
      recommendedType = "Standard_D4ds_v7"
      currentType = "Standard_D4ds_v3"
      approvalType = "all"
      savingsEstimate = "31.43"
      predictedUptime = "83.4"
      reservedInstanceCoverage = "no"
    }
  }
}

# ICO by Kubex Defaults this is used for fallback if the system name isn't found in the Kubex_recommendations. 
# This shouldn't be used in most cases likely use would be if you were to create a new system that hasn't been analyzed by Kubex yet.
variable "Kubex_fallback"{
  type = map(string)
  default = {
      	recommendedType = "Standard_D4ds_v7"
     	currentType = "Standard_D4ds_v3"
	approvalType = "all"
	savingsEstimate = "0"
	predictedUptime = "0"
	reservedInstanceCoverage = "no"
  }
}